=== AleksandraKolmakova/ITMO/ITMO.HTML&XMLCourses2023/XML Labs/Lab3/Ex1_lesson_XML.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="TimeTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="subject">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SubjectName" type="xs:string"/>
							<xs:element name="TeacherName" type="xs:string"/>
							<xs:element name="TeacherLastName" type="xs:string"/>
							<xs:element name="TeacherPatronymicName" type="xs:string"/>
							<xs:element name="Hours" type="xs:unsignedByte"/>
							<xs:element name="StartDate" type="xs:string"/>
							<xs:element name="FinalDate" type="xs:string"/>
							<xs:element name="FinalGrade" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AleksandraKolmakova/ITMO/ITMO.HTML&XMLCourses2023/XML Labs/Lab3/Ex1_lesson.xml
<?xml version="1.0" encoding="UTF-8"?>

<TimeTable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/ITMO/ITMO.HTML&amp;XMLCourses2023/XML%20Labs/Lab3/Ex1_lesson_XML.xsd">
	<subject>
		<SubjectName>Основы программирования</SubjectName>
		<TeacherName>Денис</TeacherName>
		<TeacherLastName>Ямщиков</TeacherLastName>
		<TeacherPatronymicName>Викторович</TeacherPatronymicName>
		<Hours>45</Hours>
		<StartDate>27.03.2023</StartDate>
		<FinalDate>11.04.2023</FinalDate>
		<FinalGrade>Зачет</FinalGrade>		
	</subject>
	
	<subject>
		<SubjectName>Программирование на C#</SubjectName>
		<TeacherName>Никита</TeacherName>
		<TeacherLastName>Осипов</TeacherLastName>
		<TeacherPatronymicName>Алексеевич</TeacherPatronymicName>
		<Hours>50</Hours>
		<StartDate>13.04.2023</StartDate>
		<FinalDate>28.04.2023</FinalDate>
		<FinalGrade>Зачет</FinalGrade>		
	</subject>
	
	<subject>
		<SubjectName>Введение в базы данных</SubjectName>
		<TeacherName>Ирина</TeacherName>
		<TeacherLastName>Осетрова</TeacherLastName>
		<TeacherPatronymicName>Станиславовна</TeacherPatronymicName>
		<Hours>35</Hours>
		<StartDate>01.06.2023</StartDate>
		<FinalDate>16.06.2023</FinalDate>
		<FinalGrade>Зачет</FinalGrade>		
	</subject>
</TimeTable>
